src/main/01-network.tf, src/main/02-ecr.tf, src/main/04-ecs.tf, src/main/05-alb.tf, src/main/README.md, src/main/env/uat/terraform.tfvars
=> Ecs task definition service and ALB

CODEOWNERS, src/README.md, src/main/01-network.tf, src/main/98-variables.tf
=> Vpc private endpoints

src/main/03-iam.tf, src/main/README.md
=> IAM Policy DynamoDB table read write

src/main/07-api-gateway.tf, src/main/README.md
=> Restapi with apikey and open api

src/main/01-network.tf, src/main/03-iam.tf, src/main/04-ecs.tf, src/main/06-nlb.tf, src/main/07-api-gateway.tf, src/main/10-dynamodb.tf, src/main/11-redis-cache.tf
=> Tags refactoring

src/main/00-main.tf, src/main/01-network.tf, src/main/02-ecr.tf, src/main/03-iam.tf, src/main/04-ecs.tf, src/main/06-nlb.tf, src/main/07-api-gateway.tf, src/main/10-dynamodb.tf, src/main/11-redis-cache.tf
=> Tagging refactiring

src/main/00-main.tf, src/main/03-iam.tf, src/main/README.md, src/main/iam_policies/deploy-ecs.json.tpl
=> Deploy IAM user for ECS

src/main/01-network.tf, src/main/03-iam.tf, src/main/04-ecs.tf, src/main/06-nlb.tf, src/main/07-api-gateway.tf, src/main/11-redis-cache.tf, src/main/README.md, src/main/iam_policies/deny-access-secret-devops.json.tpl
=> Deny developes access devops secret

src/main/01-network.tf, src/main/10-dynamodb.tf, src/main/README.md
=> Dynamodb endpoint refactoring

src/main/02-ecr.tf, src/main/98-variables.tf, src/main/README.md
=> Ecr lifecycle policies

src/main/10-dynamodb.tf, src/main/README.md
=> Dynamo db custom encryption key at rest.

src/main/03-iam.tf, src/main/iam_policies/allow-kms-encrypt-decrypt.json.tpl
=> Iam policy to allow ecs tasks to encryp and decrypt data with KMS

src/main/07-api-gateway.tf, src/main/README.md, src/main/terraform.sh
=> Web Acl Waf for Application gateway

src/main/04-ecs.tf, src/main/07-api-gateway.tf, src/main/10-dynamodb.tf, src/main/README.md, src/main/terraform.sh
=> Task definition env variables

src/main/07-api-gateway.tf, src/main/README.md
=> Enable cloud watch logs in api gateway api

src/main/07-api-gateway.tf, src/main/98-variables.tf, src/main/README.md
=> Rename project in pdv

src/main/07-api-gateway.tf, src/main/98-variables.tf, src/main/README.md, src/main/api/ms_tokenizer/api-docs.tpl.json
=> Update open api spec tokenizer ms

src/main/03-iam.tf, src/main/08-api-tokenizer.tf, src/main/12-dynamodb-tables.tf, src/main/README.md, src/main/api/ms_tokenizer/api-docs.tpl.json
=> Refactor open api tokenizer

src/main/00-main.tf, src/main/10-kms.tf, src/main/12-dynamodb-tables.tf, src/main/README.md
This change has no effect other than in production.
---
=> Dynamodb table replica for production only

src/main/04-ecs.tf, src/main/06-nlb.tf, src/main/12-dynamodb-tables.tf
=> Change nlb health check path

src/main/03-iam.tf, src/main/05-public-dns.tf, src/main/12-dynamodb-tables.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/uat/terraform.tfvars, src/main/outputs.tf
=> Public DNS zone

src/main/05-public-dns.tf, src/main/08-api-tokenizer.tf, src/main/11-certs.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/uat/terraform.tfvars
=> Api gateway custom domain with https

src/main/12-dynamodb-tables.tf, src/main/98-variables.tf, src/main/README.md
=> Disable by default dynamodb regional replica

src/main/03-iam.tf, src/main/12-dynamodb-token.tf, src/main/13-dynamodb-person.tf, src/main/99-refactor.tf, src/main/README.md, src/main/outputs.tf
=> Dynamodb table Person

src/main/13-dynamodb-person.tf
=> Global secondary index table Person

src/main/20-public-dns.tf, src/main/31-api-tokenizer.tf, src/main/32-api-person.tf, src/main/98-variables.tf, src/main/README.md, src/main/api/ms_person/api-docs.tpl.json, src/main/env/uat/terraform.tfvars
=> Api person api gateway

src/main/80-alarms.tf, src/main/README.md, src/main/env/uat/terraform.tfvars
=> Created sns topic to send notifications

src/main/03-iam.tf
=> Allow delete item in task policy

src/main/12-dynamodb-token.tf, src/main/13-dynamodb-person.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/uat/terraform.tfvars
=> Dynamodb point in time recovery

src/main/02-ecr.tf, src/main/07-task-user-registry.tf, src/main/40-nlb.tf, src/main/98-variables.tf, src/main/README.md
=> First draft config ms user registry

src/main/01-network.tf, src/main/07-task-user-registry.tf, src/main/33-api-user-registry.tf, src/main/98-variables.tf, src/main/README.md, src/main/api/ms_user_registry/api-docs.tpl.json, src/main/env/uat/terraform.tfvars, src/main/outputs.tf
=> Api ms user registry

src/main/04-ecs.tf
=> Scaling policy for all Ecs services

src/main/05-task-tokenizer.tf, src/main/06-task-person.tf, src/main/07-task-user-registry.tf
=> add env vars

src/main/api/ms_person/api-docs.tpl.json, src/main/api/ms_tokenizer/api-docs.tpl.json, src/main/api/ms_user_registry/api-docs.tpl.json
=> update openapi docs

src/main/02-ecr.tf, src/main/04-ecs.tf, src/main/08-task-poc.tf, src/main/40-nlb.tf, src/main/98-variables.tf, src/main/README.md, src/main/api/ms_user_registry/api-docs.tpl.json
=> Test rewrite http headers

src/init/README.md, src/init/env/prod/backend.tfvars, src/init/env/prod/terraform.tfvars, src/init/main.tf
=> Setup terraform prod

src/main/33-api-user-registry.tf, src/main/api/ms_user_registry/api-docs.tpl.json
=> Ms user registry assign the x-pagopa-namesapce from the api key id

src/main/env/prod/terraform.tfvars
=> Api gateway Custom domain with tls cert

src/main/04-ecs.tf, src/main/09-ecs-autoscale.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> Ecs prod autoscaling

src/azuredevops/.terraform.lock.hcl, src/azuredevops/00-main.tf, src/azuredevops/03-secrets.tf, src/azuredevops/04-service_connections.tf, src/azuredevops/README.md, src/init/.terraform.lock.hcl, src/pipelines/deploy-pipelines.yml
=> Iac pipeline prod

src/main/.terraform.lock.hcl, src/main/32-api-tokenizer.tf, src/main/33-api-person.tf, src/main/34-api-user-registry.tf
=> Assign tag name to the api log groups

src/main/05-task-tokenizer.tf, src/main/06-task-person.tf, src/main/07-task-user-registry.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> Log level error ms for prod.

src/main/api/ms_person/api-docs.tpl.json, src/main/api/ms_user_registry/api-docs.tpl.json
=> Fix api multivalues query string openapi integration

src/main/api/ms_user_registry/api-docs.tpl.json
=> Fix get querystring params duplicate

src/main/13-dynamodb-person.tf
It may be necessary to clear (or in worst case, recreate) the table in order to apply this change!
---
=> fix gsi_namespaced_id projection_type

src/main/.terraform.lock.hcl, src/main/01-network.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/uat/terraform.tfvars, src/main/outputs.tf
=> Vpc peering 2 tokenizer

src/main/07-task-user-registry.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/uat/terraform.tfvars
=> Update tokenizer ms host name

src/main/15-cloudhsm.tf, src/main/README.md, src/main/env/prod/terraform.tfvars, src/main/outputs.tf
=> VPC Peering tokenizer prod

src/main/15-cloudhsm.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> Cloudhsm config for testing in production

src/main/env/prod/terraform.tfvars, src/main/env/uat/terraform.tfvars
=> New api keys in uat for PNPF

src/main/33-api-user-registry.tf, src/main/README.md
=> Api stage version in api path mapping

src/main/33-api-user-registry.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> Api alarms

src/main/33-api-user-registry.tf, src/main/98-variables.tf, src/main/README.md
=> Disable api data trace

src/main/14-dynamodb-alarms.tf
=> Dynamodb alerts

src/main/env/uat/terraform.tfvars
Added three api keys
Enable access for a common sandboxed test and to self care
---
=> Add Self Care Api Keys for Self Care and  sandbox

src/main/09-ecs-autoscale.tf, src/main/98-variables.tf, src/main/README.md
=> Ecs alerts

src/main/env/uat/terraform.tfvars
Added api key due to interop prroduct
---
=> Added api key due to interop dev and uat

src/main/06-task-person.tf, src/main/07-task-user-registry.tf
=> Removed task healthcheck

src/main/11-certs.tf, src/main/20-public-dns.tf, src/main/98-variables.tf, src/main/README.md
=> Update ttl dns records

src/main/41-nlb-alarms.tf, src/main/README.md
=> Network load balancer alarms

src/main/41-nlb-alarms.tf
=> Refactor nlb alert names

src/main/33-api-user-registry.tf, src/main/README.md
=> Alarm api low latency

src/main/33-api-user-registry.tf, src/main/api/ms_user_registry/api-docs.tpl.json, src/main/api/ms_user_registry/status_code_mapping.tpl.json
=> Fix wrong response status code

src/main/api/ms_user_registry/api-docs.tpl.json, src/main/api/ms_user_registry/status_code_mapping.tpl.json
@uolter ho visto che non in tutte le API è presente il 429 come possibile response code, è corretto? Tale policy è stata configurata solo per un subset di API?
---
=> fix response codes

src/main/30-api-gateway.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> Sql injection web acl rule set

src/main/50-cloudwatch.tf, src/main/cloudwatch-query/apigw-429.sql, src/main/cloudwatch-query/count-api-rate-limit.sql, src/main/cloudwatch-query/log-level-error.sql, src/main/cloudwatch-query/log-with-exception.sql
=> Cloudwatch query definitions

src/main/env/prod/terraform.tfvars
@iwoak I've called this key just **TEST**. I'd like to use it to run any test in production: not only the load test. Is it fine with you?
---
=> New api key for testing in production

src/main/32-webacl.tf, src/main/README.md
=> Fix webacl rule metric names

src/main/50-cloudwatch.tf, src/main/cloudwatch-query/count-provisioned-throughput-exceeded.sql
=> Query dynamodb throttling

src/main/env/prod/terraform.tfvars
Add api key to interop team
Need access to pdv
---
=> add api key to interop

src/pipelines/deploy-pipelines.yml
=> Fix wrong ref in azure pipeline

src/main/.terraform.lock.hcl, src/main/60-sentinel.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> Change sentinel module

src/main/env/prod/terraform.tfvars
This integration is now configured at the organisation  level
---
=> Disable sentinel in production

src/main/30-api-gateway.tf, src/main/34-api-docs.tf, src/main/70-storage.tf, src/main/README.md, src/main/outputs.tf, src/main/templates/s3_policy.tpl.json
=> Openapi export

src/main/env/prod/terraform.tfvars
=> Api key piattaforma notifiche

src/main/env/uat/terraform.tfvars
=> Idpay plan for uat

.github/workflows/terraform-apply.yml
=> Fix environment when missed

.github/workflows/terraform-apply.yml, CODEOWNERS
=> Fix environment apply action

.github/workflows/apply/action.yml, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
=> Github actions with hashes

.github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
=> Github actions env name

.github/workflows/apply/action.yml, .github/workflows/terraform-apply.yml
=> Fix string substitution

src/main/env/prod/terraform.tfvars
=> Idpay prod config

src/main/14-dynamodb-alarms.tf, src/main/env/prod/terraform.tfvars
=> config: Change table person autoscaling parameters

src/main/04-ecs.tf, src/main/06-task-person.tf, src/main/07-task-user-registry.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> config: Change autoscaling config

src/main/env/prod/terraform.tfvars, src/main/env/uat/terraform.tfvars
=> config: New keys pnpfg

src/main/51-dashboard.tf, src/main/dashboards/main.tpl.json
=> fix: Rate limit query in cloudwatch dashboard

src/main/env/prod/terraform.tfvars
=> feat: Change Interop PROD api rate limit

src/main/03-iam.tf, src/main/98-variables.tf, src/main/README.md, src/main/outputs.tf
=> feat: Role to allow github to deploy on ECS

src/main/iam_policies/deploy-ecs.json.tpl
=> fix: Update iam policy to allow github action to deploy in ECS

.github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
=> chore: Update task versions in github actions

src/main/03-iam.tf, src/main/iam_policies/deploy-ecs.json.tpl
=> fix: Update policy to allow github action to deploy new ecs task

src/main/03-iam.tf
=> feat: Restrict iam role to allow only main branch 

src/main/40-nlb.tf, src/main/README.md
=> fix: Pinned nlb module version 

src/main/20-public-dns.tf
=> feat: Change api dns record to record A

src/main/03-iam.tf, src/main/98-variables.tf, src/main/README.md
=> fix: Iam policy condition missed github repo

src/main/cloudwatch-query/apigw-429.sql, src/main/cloudwatch-query/count-api-rate-limit.sql, src/main/env/prod/terraform.tfvars
=> feat: Update selfcare and interop rate limits

src/main/33-api-user-registry.tf, src/main/34-api-docs.tf, src/main/README.md
=> fix: Open api missed descriptions

src/main/dashboards/main.prod.bak, src/main/dashboards/main.tpl.json
=> fix: Cloudwatch dashboard widget 429 count

src/main/.terraform.lock.hcl, src/main/00-main.tf, src/main/README.md, src/main/env/uat/terraform.tfvars
=> feat: New api key for pnpf cert uat

CODEOWNERS, src/main/env/prod/terraform.tfvars
=> feat: Ecs autoscaling configuration updates

src/main/env/prod/terraform.tfvars
=> feat: Update ECS replica count

README.md, src/main/40-nlb.tf
=> feat: Update nlb health check intervals

src/main/dashboards/main.json.bak, src/main/dashboards/main.tpl.json
=> fix: Update cloudwatch dashboard

src/main/33-api-user-registry.tf
=> feat: Update alarm api 5xx errors

src/main/.terraform.lock.hcl, src/main/04-iam.tf
=> fix: Missed policy to run deploy on ECS

src/main/04-iam.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> feat: Pn rate limit change config

src/main/env/uat/terraform.tfvars
=> feat: Update rate limit PN uat

CODEOWNERS
Update CODEOWNERS file removing infrastracture-admins from it
OER task
---
=> chore: Update CODEOWNERS file removing infrastracture-admins from it

.github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
Pin **ubuntu** version on Github Actions to `ubuntu-22.04`
OER task
---
=> chore: Oe 62 pin ubuntu version to ubuntu-22.04

src/main/env/prod/terraform.tfvars, src/main/env/uat/terraform.tfvars
=> feat: Update burst rate limits

src/main/32-webacl.tf
=> fix: Update webacl alarm

src/init/main.tf
=> fix: Github thumbprint

src/main/env/uat/terraform.tfvars
=> feat: Uat setup for PN Load tests

src/main/50-cloudwatch.tf, src/main/README.md
=> feat: Log insights query to count 404

README.md
=> chore: OE 78 add pipeline status badges

src/init/.terraform.lock.hcl, src/init/README.md, src/init/env/dev/backend.tfvars, src/init/env/dev/terraform.tfvars, src/init/env/uat/terraform.tfvars, src/init/main.tf, src/main/70-storage.tf, src/main/README.md, src/main/env/dev/backend.tfvars, src/main/env/dev/terraform.tfvars
=> feat: Pdv dev env

.github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
=> feat: GitHub action support for dev

src/main/env/dev/terraform.tfvars
=> feat: Setup vcp peering for dev

src/main/80-alarms.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> feat: Opsgenie integration

src/main/80-alarms.tf
=> feat: Opsgenie topic subscription confirmation timeout

src/main/33-api-user-registry.tf, src/main/80-alarms.tf, src/main/env/uat/terraform.tfvars
=> feat: Test sns filter policy in uat

src/main/env/dev/terraform.tfvars, src/main/env/prod/terraform.tfvars, src/main/env/uat/terraform.tfvars
Add `GITHUB-KEY` plan
This API Key is needed in the integration tests pipeline
---
=> feat: Add GitHub api key for testing purposes

src/main/01-locals.tf, src/main/33-api-user-registry.tf, src/main/51-dashboard.tf, src/main/80-alarms.tf, src/main/dashboards/main.tpl.json, src/main/env/uat/terraform.tfvars
=> feat: Update sns policy filter and links

src/main/33-api-user-registry.tf
=> fix: Apigw latency alarm

src/main/33-api-user-registry.tf
=> feat: Update 4xx alarm description.

src/main/01-locals.tf, src/main/33-api-user-registry.tf, src/main/80-alarms.tf, src/main/env/uat/terraform.tfvars
=> fix: Update alarm 4xx, 5xx and sns filter policy

src/main/50-cloudwatch.tf, src/main/api/velocity_request_template_write.tpl, src/main/cloudwatch-query/log-by-traceid.sql, src/main/cloudwatch-query/log-by-x-amzn-trace-id.sql
In this pull request the following changes are introduced:
- Removed hotfix from velocity request template.
- "Log by traceId" query is updated with a regex that respects the new logs' pattern.
- New query "Log by xAmznTraceId" added.
- [] Add new resources
---
=> feat: update loginsights queries

src/main/02-network.tf, src/main/03-ecr.tf, src/main/04-iam.tf, src/main/05-ecs.tf, src/main/06-task-person.tf, src/main/07-task-user-registry.tf, src/main/33-api-user-registry.tf, src/main/98-variables.tf, src/main/env/dev/terraform.tfvars, src/main/env/prod/terraform.tfvars, src/main/env/uat/terraform.tfvars, src/main/outputs.tf
=> feat: add AWS X-Ray infra configurations

src/main/33-api-user-registry.tf
=> feat: Update alarm 4xx treshold

src/main/dashboards/main.tpl.json
=> Update dynamodb widget

src/main/05-ecs.tf, src/main/98-variables.tf, src/main/README.md, src/main/env/prod/terraform.tfvars
=> Enable container insight

src/main/05-ecs.tf
=> Fix container insights settings

src/main/14-dynamodb-alarms.tf, src/main/README.md
=> Removed dynamodb Exceeding Throughput

src/main/33-api-user-registry.tf, src/main/34-api-docs.tf
=> Disable execute api endpoints

src/main/api/ms_user_registry/api-docs.tpl.json
=> feat: update openapi spec with new WorkContact resources

src/main/33-api-user-registry.tf, src/main/98-variables.tf, src/main/env/prod/terraform.tfvars
=> feat: Update 4xx alarm threshold

src/main/cloudwatch-query/log-count-404-user-reg.sql
=> fix: Update cw query 404 by namespace

README.md
=> feat: Restored readme file
